### PR TITLE
💥 217 bytes using Odog8's approach

### PR DESCRIPTION
**Pull request by p01**

### CODE REVIEW

**Comment by xem** [comment]
Love this approach! However, it breaks the uniqueness of misplaced letters:
Here for example, only one yellow should be visible.
(My 219b branch breaks it too :/ )

image

**Comment by p01** [comment]
Agreed
We can go back to the other PR I had if you want a more "proper" version

**Comment by xem** [comment]
no prob, you can keep both open, I'll try to start from your 217b code and see if I can reintroduce this feature while staying below 273 :)
I'll keep the super golfed version somewhere in the repo, for fun

**Comment by xem** [comment]
added a 202b micro.html file using these tricks

**Pull request closed without merging**
