### PR TITLE
🧑‍🏫 291 bytes

### PR DESCRIPTION
**Pull request by p01**

### CODE REVIEW

**Comment by xem** [comment]
damn, I was gonna push a >300b update, but I guess I won't :p

**Comment by xem** [comment]
@p01 I can't see green squares... is it a bug or a problem on my side?

image

**Comment by xem** [comment]
other bug found:

here, in "feral", the last square should be black as there's no L in the answer, and the first square should be non-black

image

**Comment by p01** [comment]
Sorry, I did some renaming ( and added comments ) just before sending the PR, but also realized the 🟨 pass didn't skip the 🟩 squares 🙈

291 bytes

**Comment by xem** [comment]
Still seems broken, sorry... black and yellow seem inverted, green doesn't appear
image

**Comment by p01** [comment]
I'm having a Monday. I forgot to remove the broken 🟨 pass.

Hope I didn't mess up anything else this time.

**Comment by xem** [comment]
Almost perfect: your version allows for 7 guesses instead of 6 (but I can take care of it)

**Pull request merged**
