### PR TITLE
🪴 221 bytes

### PR DESCRIPTION
**Pull request by p01**
I must have tested wrong 🧐

### CODE REVIEW

**Comment by xem** [comment]
it breaks on multiple misplaced letters :)
image

**Comment by p01** [comment]
Yep, just tested that.

**Comment by p01** [comment]
Would be super nice to have some manual tests when golfing these.

For the FFT one, I could compare the output against a previous version but this one is a little more manual.

**Comment by xem** [comment]
I can do this!

**Comment by xem** [comment]
Is it ok?
https://twitter.com/MaximeEuziere/status/1488974701347196928

**Pull request closed without merging**
